import path from 'node:path';
import * as vscode from 'vscode';
import { findLibreOffice } from './libreOfficeLocator.js';
import { convertPptxToPdf } from './pptxToPdf.js';
import { PreviewError, messages } from './errors.js';
function esc(s) { return String(s).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
export class PreviewPanel {
  static panels = new Map();
  static open(context, pptxPath, output) { const key = path.resolve(pptxPath); const existing = this.panels.get(key); if (existing) { existing.panel.reveal(); existing.refresh(); return existing; } const panel = vscode.window.createWebviewPanel('pptxPreview', `PPTX: ${path.basename(pptxPath)}`, vscode.ViewColumn.Beside, { enableScripts: true, localResourceRoots: [vscode.Uri.file(path.join(context.extensionPath, 'webview'))] }); const preview = new PreviewPanel(context, panel, pptxPath, output); this.panels.set(key, preview); preview.refresh(); return preview; }
  constructor(context, panel, pptxPath, output) { this.context=context; this.panel=panel; this.pptxPath=pptxPath; this.output=output; this.running=false; this.currentWorkspace=null; this.abort=null; panel.onDidDispose(() => this.dispose()); panel.webview.onDidReceiveMessage(msg => { if (msg?.type === 'refresh') this.refresh(); }); this.renderShell(); }
  dispose() { PreviewPanel.panels.delete(path.resolve(this.pptxPath)); this.abort?.abort(); this.currentWorkspace?.dispose(this.output); }
  post(m) { try { this.panel.webview.postMessage(m); } catch { /* disposed */ } }
  renderShell() { const wv=this.panel.webview; const nonce=String(Date.now()); const script=wv.asWebviewUri(vscode.Uri.file(path.join(this.context.extensionPath,'webview','viewer.js'))); const css=wv.asWebviewUri(vscode.Uri.file(path.join(this.context.extensionPath,'webview','viewer.css'))); const pdfjs=wv.asWebviewUri(vscode.Uri.file(path.join(this.context.extensionPath,'webview','pdf.mjs'))); const worker=wv.asWebviewUri(vscode.Uri.file(path.join(this.context.extensionPath,'webview','pdf.worker.mjs'))); this.panel.webview.html = `<!doctype html><html><head><meta charset="UTF-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src ${wv.cspSource} data:; style-src ${wv.cspSource}; script-src 'nonce-${nonce}'; worker-src ${wv.cspSource} blob:;"><link rel="stylesheet" href="${css}"><title>${esc(path.basename(this.pptxPath))}</title></head><body><header><div><h1>${esc(path.basename(this.pptxPath))}</h1><p id="status">Ready</p></div><button id="refresh">Refresh</button></header><main><div id="error" hidden></div><div id="slides"></div></main><script nonce="${nonce}">window.__PDFJS_URL__=${JSON.stringify(String(pdfjs))};window.__PDFJS_WORKER_URL__=${JSON.stringify(String(worker))};</script><script nonce="${nonce}" type="module" src="${script}"></script></body></html>`; }
  async refresh() { if (this.running) return; this.running=true; this.abort = new AbortController(); this.post({ type:'loading' }); try { const lo = await findLibreOffice(); if (!lo.found) throw new PreviewError('libreOfficeMissing', messages.libreOfficeMissing, `Checked: ${lo.candidates.join(', ')}`); const result = await convertPptxToPdf({ pptxPath:this.pptxPath, libreOfficePath:lo.path, signal:this.abort.signal, logger:this.output }); await this.currentWorkspace?.dispose(this.output); this.currentWorkspace = result.workspace; const pdfUri = this.panel.webview.asWebviewUri(vscode.Uri.file(result.pdfPath)); this.post({ type:'pdf', uri:String(pdfUri) }); } catch (e) { const pe = e instanceof PreviewError ? e : new PreviewError('unknown', 'PPTX preview failed.', e?.message ?? String(e), e); this.output.appendLine(`[${pe.code}] ${pe.detail}`); this.post({ type:'error', code:pe.code, message:pe.userMessage }); } finally { this.running=false; this.abort=null; this.post({ type:'idle' }); } }
}
export { esc as escapeHtml };
